/* Generated By:JJTree: Do not edit this line. ASTEXCLAMATION.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTEXCLAMATION extends BooleanOperator {
  public ASTEXCLAMATION(int id) {
    super(id);
  }

  public ASTEXCLAMATION(JmmParser p, int id) {
    super(p, id);
  }

  public void applySemanticAnalysis(Table table) throws Exception {
    SimpleNode child = ((SimpleNode) children[0]);
    checkSide(child, table);
  }
}
/* JavaCC - OriginalChecksum=824c554e1b735c6561b8b3d2683ac32d (do not edit this line) */
