/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(JmmParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=075144479f16b728bb9372069358f2f1 (do not edit this line) */
