/* Generated By:JJTree: Do not edit this line. ASTINTEGER.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTINTEGER extends SimpleNode {
  public ASTINTEGER(int id) {
    super(id);
  }

  public ASTINTEGER(JmmParser p, int id) {
    super(p, id);
  }

  public String toString(String prefix) {
    this.print = this.name;
    return prefix + this.print;
  }
}
/* JavaCC - OriginalChecksum=4cf8735d574ee13c717e8d9b4a44ba4f (do not edit this line) */
