/* Generated By:JJTree: Do not edit this line. ASTmainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTmainDeclaration extends SimpleNode {
  public ASTmainDeclaration(int id) {
    super(id);
  }

  public ASTmainDeclaration(JmmParser p, int id) {
    super(p, id);
  }

  public void createTable(Table table) {
    Table methodTable = new Table(table, "void");
    JmmParser.getInstance().addMethod("main", methodTable);
    Symbol symbol = new Symbol("String[]", ((SimpleNode) children[2]).name, Symbol.Access.parameter);
    methodTable.addSymbol(symbol);

    if (children == null)
      return;

    for (int i = 0; i < children.length; i++) {
      ((SimpleNode) children[i]).createTable(methodTable);
    }
  }

  public void applySemanticAnalysis(Table table) throws Exception {
    Table methodTable = JmmParser.getInstance().getMethods().get("main");

    if (children == null)
      return;

    for (int i = 0; i < children.length; i++) {
      ((SimpleNode) children[i]).applySemanticAnalysis(methodTable);
    }
  }
}
/* JavaCC - OriginalChecksum=e7fcc2d4fe899ca3af7d1447a5df4425 (do not edit this line) */
