/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(JmmParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72f2a283fb8314b51149acc85034ff99 (do not edit this line) */
