/* Generated By:JJTree: Do not edit this line. ASTTRUE.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTRUE extends SimpleNode {
  public ASTTRUE(int id) {
    super(id);
  }

  public ASTTRUE(JmmParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c5afba8778f519c016f300c8bf5e541 (do not edit this line) */
