/* Generated By:JJTree: Do not edit this line. ASTtype.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTtype extends SimpleNode {
  public ASTtype(int id) {
    super(id);
  }

  public ASTtype(JmmParser p, int id) {
    super(p, id);
  }

  public String getType() {
    if (children.length == 1 && ((SimpleNode) children[0]).index != -1)
      return JmmParserConstants.tokenImage[((SimpleNode) children[0]).index].replaceAll("\"", "");

    if (children.length == 1)
      return ((SimpleNode) children[0]).name;

    return "int[]";
  }

  public void applySemanticAnalysis(Table table) throws Exception {
      SimpleNode lhs = ((SimpleNode) children[0]);

      if(lhs.name != null){
        if(!JmmParser.getInstance().getClassTable().getType().equals(lhs.name))
            throw new Exception("Class not found");
      }

      if (children == null)
          return;

      if (print.equals("extends")) {
          extend = ((SimpleNode) children[0]).getName();
      }

      for (int i = 0; i < children.length; i++) {
          ((SimpleNode) children[i]).applySemanticAnalysis(table);
      }
  }
}
/* JavaCC - OriginalChecksum=98782c5d64cb310b07b648e3a202d21f (do not edit this line) */
