/* Generated By:JJTree: Do not edit this line. ASTvarDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTvarDeclaration extends SimpleNode {
  public ASTvarDeclaration(int id) {
    super(id);
  }

  public ASTvarDeclaration(JmmParser p, int id) {
    super(p, id);
  }

  public void createTable(Table table) {
    Symbol.Access access;
    String type;

    if (table.getParent() == null)
      access = Symbol.Access.global;
    else
      access = Symbol.Access.local;

    ASTtype typeNode = (ASTtype) children[0];
    type = typeNode.getType();

    Symbol symbol = new Symbol(type, ((SimpleNode) children[1]).name, access);
    table.addSymbol(symbol);
  }
}
/* JavaCC - OriginalChecksum=e8e7e4f9b7bbe78607035a31121328ba (do not edit this line) */
